 #!/bin/zsh
 cp Configurations.txt ./TestEndFollowRejectState.txt 
 cp Configurations.txt ./TestMAInTA.txt 
 cp Configurations.txt ./TestTAFollowMA.txt 
 cp Configurations.txt ./TestTransitionSecondChar.txt 
 cp Configurations.txt ./TestAcceptStateFollowInitState.txt 
 cp Configurations.txt ./TestInitStateFollowTransition.txt 
 cp Configurations.txt ./TestRejectStateFollowAcceptState.txt 
 cp Configurations.txt ./TestTapeAlphabet.txt 
 cp Configurations.txt ./TestTransitionsFollowTA.txt 
 cp Configurations.txt ./TestAcceptStateInTransition.txt 
 cp Configurations.txt ./TestInitStateInStates.txt 
 cp Configurations.txt ./TestRejectStateInTransition.txt 
 cp Configurations.txt ./TestTransitionFirstChar.txt 
 cp Configurations.txt ./TestTransitionThirdChar.txt 
 cp Configurations.txt ./TestAcceptStateNotInStates.txt 
 cp Configurations.txt ./TestInitStateSingleWord.txt  
 cp Configurations.txt ./TestRejectStateNotInStates.txt 
 cp Configurations.txt ./TestTransitionFithChar.txt 
 cp Configurations.txt ./TestAcceptState.txt 
 cp Configurations.txt ./TestMachineAlphabet.txt 
 cp Configurations.txt ./TestRejectState.txt 
 cp Configurations.txt ./TestTransitionForm.txt
 cp Configurations.txt ./TestBeginByState.txt
 cp Configurations.txt ./TestMAFollowState.txt
 cp Configurations.txt ./TestState.txt
 cp Configurations.txt ./TestTransitionForthChar.txt
 cp Configurations.txt ./TestAlreadyInTransition.txt